### ISSUE TITLE
Request: Cursor should not blink while typing and deleting words

### ISSUE THREAD

**Issue by adarah** [awran5/react-simple-typewriter#10]
It's bothering me a little that the cursor blinks while typing or deleting, this is not how regular cursors behave.

And as an extra request, could you also expose an `onDelete` function which is invoked for every deleted key (similar to onType)? I would be using this to implement my own custom cursor (I'd like to change the blinking timing, but I don't think it's worth exposing more cursor configs in this library's API)

**Comment by awran5** [comment]
@adarah 

Now you can achieve that by using [hook](https://github.com/awran5/react-simple-typewriter#2-hook) with the new version v5.


```jsx
import { useTypewriter, Cursor } from 'react-simple-typewriter'
 
const TypewriterComponent = () => {
  const [text, flags] = useTypewriter({
    /* your config */
  });

  const { isDelay } = flags;

  return(
    <div>
      <span>{text}</span>
      <Cursor cursorBlinking={isDelay} />
    </div>
  );
};
```

as for your request, I've add a new [callbacks](https://github.com/awran5/react-simple-typewriter#component-props) too:

-  onType
-  onDelay
-  onDelete

**Comment by adarah** [comment]
Perfect, thank you so much!
