### ISSUE TITLE
How to run only once?

### ISSUE THREAD

**Issue by Shpigford** [awran5/react-simple-typewriter#12]
How can I get the typewriter effect to just run once and leave the text as-is?

I don't want any text deleted. Just want to type out a sentence and leave it displayed.

**Comment by awran5** [comment]
Hi @Shpigford This actually the default behavior, just use the component as so:

```jsx
// add `cursor` as a prop if you want the cursor effect
<Typewriter words={['This text will run only once!']} />
```

**Comment by Shpigford** [comment]
@awran5 Ah! I was including a bunch of other props unnecessarily. Thanks!
