### ISSUE TITLE
Update package to use latest react version

### ISSUE THREAD

**Issue by kaf-lamed-beyt** [awran5/react-simple-typewriter#2]
When I tried making (installing) use of this package, I get an error in my terminal, which is due to the versions of react conflicting with each othet. Mine is `react@"17.0.2"` while that of the package is `react@"^16.0.0"`.

For me to be able to get it to work. I'd have to run the command by adding the `--force` or `--legacy-peer-deps` flag
```npm
npm install react-simple-typewriter --force || --legacy-peer-deps
```

I'd love to take on this issue.

**Comment by awran5** [comment]
Hello @Caleb335 Sorry for the late answer. 

Thanks for reporting this back. Its fixed now in the latest version.
